import { RawAnswers } from "./types";

/** Sample profiles for "preview a sample profile" — invented, never real user
    data, and never derived from anyone's answers. Both are marked as detailed
    checks because they carry the expanded instruments; a quick-check persona
    would have to leave half these fields undefined. */
export const PERSONAS: Record<string, RawAnswers> = {
  "running-hot": {
    depth: "detailed",
    name: "Sam",
    age: "19-25",
    region: "us",
    situation: "University",
    sleepHours: 6.5,
    sleepReg: 2,
    sleepQual: 2,
    sleepLatency: 3,
    sleepScreens: 4,
    chrono: "owl",
    wake: 8,
    workload: 3,
    phq: [1, 1, 2, 1, 1, 1, 1, 1, 0],
    phqExpanded: true,
    gad: [2, 2, 2, 1, 1, 1, 1],
    gadExpanded: true,
    bo: [3, 3, 3],
    audit: [2, 2, 1],
    move: 3,
    meals: 2,
    hydrate: 2,
    social: 2,
    screenEve: 3,
    recovery: 3,
    environment: 1,
    purpose: 2,
    goal: "Grades / exams",
  },
  steady: {
    depth: "detailed",
    name: "Alex",
    age: "16-18",
    region: "uk",
    situation: "School",
    sleepHours: 7.5,
    sleepReg: 0,
    sleepQual: 1,
    chrono: "between",
    wake: 7,
    workload: 1,
    phq: [0, 1],
    phqExpanded: false,
    gad: [1, 0],
    gadExpanded: false,
    bo: [1, 1, 1],
    audit: [0],
    move: 1,
    meals: 0,
    hydrate: 1,
    social: 0,
    screenEve: 1,
    recovery: 1,
    environment: 0,
    purpose: 1,
    goal: "Build consistent routines",
  },
};
